name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    

#defaults:
#  run:
#    working-directory: src

jobs:
  build:

    runs-on: ubuntu-latest
   # runs-on: ${{ matrix.os }}
   # strategy:
   #   matrix:
   #     node_version: ['8', '10', '12']
   #     os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: DotNet Publish
      run: dotnet publsh --configuration Release -o ${{ github.workspace }}/package
      
    - name: Upload
      uses: actions/upload-artifacts@v1
      with: 
        name: app
        path: ${{ github.workspace }}/package
